version: "2"
linters:
  enable:
    - asciicheck
    - dogsled
    - dupl
    - gocognit
    - gocritic
    - gocyclo
    - lll
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - staticcheck
    - unparam
    - whitespace
  settings:
    gocognit:
      min-complexity: 35
    lll:
      line-length: 300
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
