project_name: movelooper

builds:
  - main: ./main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    files:
      - ./dist/*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
